import { Inter } from "next/font/google";
import Providers from "@/app/Providers.tsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<Providers>
				<body className={`${inter.className} min-h-screen`} data-theme="dark">
					{children}
				</body>
			</Providers>
		</html>
	);
}
